### PR TITLE
& -> and

### PR DESCRIPTION
**Pull request by dougproctor**

### CODE REVIEW

**Review by dproctor — APPROVED** [review]
Did you manage to get jekyll installed and figure out how to serve the site locally?

**Comment by dougproctor** [comment]
No, I tried but was not able to get jekyll working...

**Comment by dproctor** [comment]
OK, one easy thing you can do is to just clone this repo, and turn on
github pages from the new github repo. Then, whenever you push your changes
there, you can see the change live at the github pages url.

It takes maybe 30 sec or so for the changes to go live, but it doesn't
require installing any software on your machine.

**Comment by dproctor** [comment]
Thanks, Doug for sending over those patches.

However, in general, it'd be easier if you either pushed all of those to a
branch (e.g.
https://github.com/dproctor/katie-doug-wedding-site/tree/doug-proposed-changes)
or you consolidated them into fewer PRs. There were some conflicting
changes that I had to merge, which isn't ideal.

Devon

**Pull request merged**
